name: fifa_2026_live_score_update
description: Fifa 2026 Live Score Update App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  intl: ^0.20.2
  shimmer: ^3.0.0
  # dot_matrix_text: ^0.2.1 
  flutter_dotenv: ^6.0.1 
  dio: ^5.9.2
  flutter_riverpod: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/stadiums/
    - .env
  fonts:
    - family: BarlowCondensed
      fonts:
        - asset: assets/fonts/BarlowCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/BarlowCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BarlowCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/BarlowCondensed-ExtraBold.ttf
          weight: 800
