name: fifa_2026_live_score_update
description: Fifa 2026 Live Score Update App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  intl: ^0.20.2
  shimmer: ^3.0.0
  # dot_matrix_text: ^0.2.1 
  flutter_dotenv: ^6.0.1 
  dio: ^5.9.2
  flutter_riverpod: ^3.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"

flutter_native_splash:
  android: true
  ios: true

  color: "##1E1E1E"
  image: "assets/images/splash.png"
  branding: "assets/images/branding.png"

  android_12:
    color: "#1E1E1E"
    image: "assets/images/android_12_splash_on_charge.png"
    branding: "assets/images/branding.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/stadiums/
    - assets/images/
    - .env
  fonts:
    - family: BarlowCondensed
      fonts:
        - asset: assets/fonts/BarlowCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/BarlowCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BarlowCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/BarlowCondensed-ExtraBold.ttf
          weight: 800
